name: Python Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        node-version: '16'
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        node-version: '16'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: pytest
